export const ERROR_CODES: Record<string, string> = {
  ERR_UNAUTHORIZED: 'Sesi tidak valid, silakan login ulang',
  ERR_FORBIDDEN: 'Anda tidak memiliki akses',
  ERR_ACCOUNT_DISABLED: 'Akun Anda dinonaktifkan',
  ERR_IP_NOT_WHITELISTED: 'IP Anda tidak diizinkan',
  ERR_NOT_FOUND: 'Data tidak ditemukan',
  ERR_VALIDATION: 'Data tidak valid',
  ERR_INVALID_PHONE: 'Format nomor telepon tidak valid',
  ERR_INVALID_REGEX: 'Pola regex tidak valid',
  ERR_INVALID_IP_FORMAT: 'Format IP/CIDR tidak valid',
  ERR_INVALID_TIME_FORMAT: 'Format waktu harus HH:MM',
  ERR_SCHEDULE_PAST: 'Waktu jadwal sudah lewat',
  ERR_DUPLICATE_SESSION_NAME: 'Nama sesi sudah digunakan',
  ERR_DUPLICATE_CONTACT: 'Kontak sudah ada',
  ERR_DUPLICATE_TEMPLATE_NAME: 'Nama template sudah digunakan',
  ERR_DUPLICATE_DRIP_DAY: 'Day offset sudah ada di step lain',
  ERR_SESSION_NOT_CONNECTED: 'Sesi WhatsApp tidak terhubung',
  ERR_SESSION_LOGGED_OUT: 'Sesi logout permanen, scan ulang QR',
  ERR_SESSION_NOT_FOUND: 'Sesi tidak ditemukan',
  ERR_NO_SESSIONS: 'Tidak ada sesi WhatsApp aktif',
  ERR_NO_RECIPIENTS: 'Tidak ada penerima broadcast',
  ERR_QUOTA_DAILY_EXCEEDED: 'Kuota pesan harian habis',
  ERR_QUOTA_MONTHLY_EXCEEDED: 'Kuota broadcast bulanan habis',
  ERR_RATE_LIMIT: 'Terlalu banyak request, coba lagi nanti',
  ERR_2FA_INVALID_CODE: 'Kode 2FA tidak valid',
  ERR_2FA_SESSION_EXPIRED: 'Sesi 2FA kadaluarsa, ulangi login',
  ERR_2FA_ALREADY_ENABLED: '2FA sudah aktif',
  ERR_2FA_NOT_ENABLED: '2FA belum diaktifkan',
  ERR_CAMPAIGN_NOT_CANCELLABLE: 'Campaign tidak dapat dibatalkan',
  ERR_MESSAGE_ALREADY_SENT: 'Pesan sudah terkirim',
  ERR_WEBHOOK_NOT_CONFIGURED: 'URL webhook belum dikonfigurasi',
  ERR_FEATURE_NOT_AVAILABLE: 'Fitur ini tidak tersedia di tier Anda',
  ERR_AI_DISABLED: 'AI Smart Reply sedang tidak aktif',
  ERR_SEND_FAILED: 'Gagal mengirim pesan ke WhatsApp',
  ERR_FILE_TOO_LARGE: 'Ukuran file melebihi batas 50MB',
  ERR_FILE_TYPE_NOT_ALLOWED: 'Tipe file tidak diizinkan',
  ERR_WORKFLOW_TOO_MANY_NODES: 'Workflow maksimal 20 node',
  ERR_DELAY_TOO_LONG: 'Delay maksimal 3600 detik',
  ERR_CANNOT_DELETE_SELF: 'Tidak bisa menghapus akun sendiri',
  ERR_MAINTENANCE: 'Server sedang dalam maintenance',
  ERR_INTERNAL: 'Terjadi kesalahan internal server',
}

export function getErrorMessage(code?: string, fallback?: string): string {
  if (!code) return fallback ?? 'Terjadi kesalahan'
  return ERROR_CODES[code] ?? fallback ?? code
}
