export const SOCKET_EVENTS = {
  QR: 'qr',
  CODE: 'code',
  CONNECTION_UPDATE: 'connection_update',
  NEW_MESSAGE: 'new_message',
  MESSAGE_ACK: 'message_ack',
  MESSAGE_EDIT: 'message_edit',
  MESSAGE_REACTION: 'message_reaction',
  MESSAGE_REVOKE_EVERYONE: 'message_revoke_everyone',
  MESSAGE_REVOKE_ME: 'message_revoke_me',
  MEDIA_UPLOADED: 'media_uploaded',
  VOTE_UPDATE: 'vote_update',
  GROUP_JOIN: 'group_join',
  GROUP_LEAVE: 'group_leave',
  GROUP_ADMIN_CHANGED: 'group_admin_changed',
  GROUP_UPDATE: 'group_update',
  GROUP_MEMBERSHIP_REQUEST: 'group_membership_request',
  CONTACT_CHANGED: 'contact_changed',
  CHAT_ARCHIVED: 'chat_archived',
  CHAT_REMOVED: 'chat_removed',
  CHANGE_STATE: 'change_state',
  CHANGE_BATTERY: 'change_battery',
  INCOMING_CALL: 'incoming_call',
  BROADCAST_PROGRESS: 'broadcast_progress',
  BROADCAST_COMPLETE: 'broadcast_complete',
  SYSTEM_ALERT: 'system_alert',
} as const

export const SYSTEM_ALERT_TYPES = {
  QUOTA_WARNING: 'quota_warning',
  QUOTA_EXCEEDED: 'quota_exceeded',
  SESSION_DISCONNECTED: 'session_disconnected',
  SESSION_LOGGED_OUT: 'session_logged_out',
  ALL_SESSIONS_DOWN: 'all_sessions_down',
  AI_DISABLED: 'ai_disabled',
  DISK_WARNING: 'disk_warning',
  REDIS_DISCONNECTED: 'redis_disconnected',
  BROADCAST_COMPLETE: 'broadcast_complete',
  ANNOUNCEMENT: 'announcement',
} as const
